common:
  nodes: 8192
  linkspeed: 100000
  seed: 13

experiments:
  - name: ndp_ecmp
    exe: htsim_ndp
    traffic:
      type: permutation
      generator: gen_permutation.py
      params:
        flows: 8192
        flowsize: [2_000_000]
        extra: 0
    simulation:
      strat: ecmp
      paths: [32, 256]
      queue_size: [35, 1000]
      cwnd: 50
      mtu: 4000
      end: 300
      logtime: 0.01

  - name: ndp_ecn
    exe: htsim_ndp
    traffic:
      type: permutation
      params:
        flows: 8192
        flowsize: [2_000_000]
        extra: 0
    simulation:
      strat: ecmp_host_ecn
      paths: [32, 256]
      queue_size: [1000]
      ecn_thresh: [0.018]
      cwnd: 50
      mtu: 4000
      end: 300
      logtime: 0.01

